export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL= "REGISTER_FAIL";

export const LOGIN_SUCCESS= "LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOG_OUT= "LOG_OUT";

export const LOAD_USER= "LOAD_USER";
export const AUTH_ERROR= "AUTH_ERROR";

export const GET_COACHES= "GET_COACHES";
export const GET_COACHES_FAILS= "GET_COACHES_FAILS"
export const GET_REQUEST_COACHES= "GET_REQUES_COACHES"